name: vaex-binder
channels:
  - conda-forge
dependencies:
  - bqplot
  - numpy
  - scipy
  - pyqt
  - matplotlib
  - pyopengl
  - h5py
  - numexpr
  - astropy
  - tornado
  - cython
  - pandas
  - pip:
        - git+https://github.com/maartenbreddels/vaex#egg=vaex